import { reportPlan } from "./report-plan.js";

const esc=value=>String(value??"").replace(/[&<>"']/gu,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[char]);
const fixed=value=>Number(value).toFixed(2);
const pct=value=>`${Number(value||0)}%`;
const colors=["#0A375B","#27808F","#4A8C61","#A98138","#64748B","#8B6F47","#5E8197","#71865B"];
function simpleBars(items,value,key="competency"){return `<div class="preview-bars">${items.map((item,index)=>`<div class="preview-bar-item"><span style="height:${Math.max(8,Number(value(item))*18)}%;background:${colors[index%colors.length]}"></span><small>${esc(item[key])}</small><b>${fixed(value(item))}</b></div>`).join("")}</div>`;}
function rangePreview(items){return `<div class="preview-range"><div>${simpleBars(items,item=>item.median)}</div><img src="./assets/images/bhb-range-legend-template.png" alt="Legendă pentru minim, maxim, mediană și benchmark"></div>`;}
function benchmarkPreview(bands){const segments=[[`Mai mică de ${bands.low}`,bands.below,"#003057"],[`Între ${bands.low} – ${bands.high}`,bands.typical,"#a5a5a5"],[`Peste ${bands.high}`,bands.above,"#f8ec32"]];return `<p class="preview-note">Benchmark pe baza evaluărilor Trend: între ${bands.low} și ${bands.high} – performanță la nivel mediu.</p><div class="preview-benchmark" aria-label="Distribuția procentuală a participanților">${segments.map(([label,count,color])=>`<span style="width:${bands.n?count/bands.n*100:0}%;background:${color}"><b>${bands.n?Math.round(count/bands.n*100):0}%</b><small>${esc(label)}</small></span>`).join("")}</div>`;}
function methodologyPreview(slide){const column=(items,missing)=>`<div><h3>${esc(items[0])}</h3><ul>${items.slice(1).map(item=>`<li>${esc(item)}</li>`).join("")}</ul>${missing?`<p class="preview-missing">Completează exercițiile sau alte instrumente numai dacă sunt confirmate.</p>`:""}</div>`;return `<div class="preview-methodology">${column(slide.page.left,slide.page.missing.exercises||slide.page.missing.otherInstruments)}${column(slide.page.right,false)}</div>`;}
function summaryPreview(summary){return `<div class="preview-summary"><div class="summary-stat"><b>${summary.population}</b><span>participanți evaluați</span></div><div class="summary-stat summary-highlight"><b>${pct(summary.distribution[1]?.value)}</b><span>în intervalul benchmark</span></div><div class="summary-stat"><b>${esc(summary.strongest?.competency||"—")}</b><span>competența cel mai bine reprezentată</span></div><div class="summary-stat"><b>${esc(summary.weakest?.competency||"—")}</b><span>principală oportunitate de dezvoltare</span></div></div><div class="summary-copy"><p>Distribuția generală: ${summary.distribution.map(item=>`${pct(item.value)} ${esc(item.label.toLowerCase())}`).join(" · ")}.</p>${summary.strengths.length?`<p>Comportamente evidențiate: ${summary.strengths.map(item=>esc(item.score2||item.behavior)).join("; ")}.</p>`:""}${summary.development.length?`<p>Priorități comportamentale: ${summary.development.map(item=>esc(item.score0||item.behavior)).join("; ")}.</p>`:""}</div>`;}
function findingPreview(slide){const {item,insight}=slide;const list=(heading,items,field)=>`<div class="finding-column"><h3>${heading}</h3>${items.length?items.map((row,index)=>`<article><b>${index+1}</b><span>${esc(row[field]||row.behavior)}</span></article>`).join(""):"<p class=\"preview-missing\">Nu există comportamente detaliate confirmate.</p>"}</div>`;return `<div class="finding-score"><b>${fixed(item.mean)}</b><span>medie · mediană ${fixed(item.median)} · n ${item.n}</span></div><div class="preview-findings">${list("Comportamente evidențiate",insight.strengths,"score2")}${list("Arii prioritare de dezvoltare",insight.development,"score0")}</div>`;}
function behaviorPreview(insight){const column=(heading,items,descriptor)=>`<div><h3>${heading}</h3>${items.map((item,index)=>`<article><b>${index+1}</b><p>${esc(item[descriptor]||item.behavior)}</p></article>`).join("")}</div>`;return `<p class="preview-behavior-caption">Comportamentele sunt selectate pentru a sintetiza punctele forte și prioritățile de dezvoltare ale grupului.</p><div class="preview-behaviors">${column("Comportamente care susțin performanța",insight.strengths,"score2")}${column("Arii prioritare de dezvoltare",insight.development,"score0")}</div>`;}
function slideBody(slide,payload){
  if(slide.family==="cover")return `<div class="preview-cover"><p>CONFIDENȚIAL</p><h2>${esc(payload.metadata.clientName||payload.metadata.projectName)}</h2><span>${esc(payload.metadata.projectName)}${payload.metadata.reportDate?` · ${esc(payload.metadata.reportDate)}`:""}</span></div>`;
  if(slide.family==="executive-summary")return summaryPreview(slide.summary);
  if(slide.family==="divider"||slide.family==="appendix-divider")return `<div class="preview-divider preview-${slide.role||"appendix"}"><h2>${esc(slide.title)}</h2></div>`;
  if(slide.family==="methodology")return methodologyPreview(slide);
  if(slide.family==="range")return rangePreview(slide.items);
  if(slide.family==="ranking")return simpleBars(slide.items,item=>item.mean);
  if(slide.family==="benchmark")return benchmarkPreview(payload.bands);
  if(slide.family==="key-findings")return findingPreview(slide);
  if(slide.family==="participant-comparison")return `<div class="preview-gridchart">${slide.items.map(record=>`<div><b>${esc(record.name)}</b>${slide.ranked.map((item,index)=>`<i style="width:${record.scores[item.competency]*20}%;background:${colors[index%colors.length]}"></i>`).join("")}</div>`).join("")}</div>`;
  if(slide.family==="benchmark-summary")return `<table><thead><tr><th>Media</th><th>Participant</th></tr></thead><tbody>${slide.items.map(item=>`<tr><td>${fixed(item.score)}</td><td>${esc(item.name)}</td></tr>`).join("")}</tbody></table>`;
  if(slide.family==="competency-summary")return simpleBars(slide.ranked,item=>item.mean);
  if(slide.family==="competency-distribution")return `<p class="preview-note">n = ${slide.item.n} · mediană ${fixed(slide.item.median)} · minim ${fixed(slide.item.min)} · maxim ${fixed(slide.item.max)}</p>${simpleBars(slide.items,record=>record.scores[slide.item.competency],"name")}`;
  if(slide.family==="behavior")return behaviorPreview(slide.insight);
  if(slide.family==="conclusions")return `<p class="preview-conclusions">${esc(slide.copy)}</p>`;
  return `<div class="preview-close">Business Health Bar</div>`;
}
export function mountPreview(root,payload,options={}){const plan=reportPlan(payload,{scope:options.scope||"whole"}),sectionFor=slide=>slide.deliverable==="appendix"?"Anexă":slide.family==="cover"||slide.family==="methodology"||slide.family==="executive-summary"?"Raport principal":slide.family==="behavior"||slide.title==="Profil comportamental"?"Profil comportamental":slide.family==="close"||slide.family==="conclusions"?"Închidere":slide.family==="competency-distribution"||slide.family==="competency-summary"||slide.title==="Analiza observațiilor"?"Observații":"Rezultate",sections=[...new Map(plan.map((slide,index)=>[sectionFor(slide),index])).entries()];let selected=Math.min(Number(root.dataset.selected||0),Math.max(0,plan.length-1));const render=()=>{const slide=plan[selected];root.dataset.selected=String(selected);root.innerHTML=`<div class="preview-heading"><div><p>Previzualizare structură raport</p><h2>Raportul care va fi generat</h2></div><span>${slide.number} / ${plan.length}</span></div><nav class="preview-sections" aria-label="Secțiuni raport">${sections.map(([name,index])=>`<button type="button" data-section="${index}" class="${sectionFor(slide)===name?"selected":""}">${esc(name)}</button>`).join("")}</nav><div class="preview-layout"><nav class="preview-thumbnails" aria-label="Slide-uri raport">${plan.map((item,index)=>`<button type="button" data-slide="${index}" class="${index===selected?"selected":""}" aria-label="Slide ${index+1}: ${esc(item.title)}"><b>${index+1}</b><span>${esc(item.title)}</span>${item.deliverable==="appendix"?`<em>Anexă</em>`:""}</button>`).join("")}</nav><section class="preview-stage-wrap"><div class="preview-stage" tabindex="0" aria-label="Previzualizare slide ${slide.number}: ${esc(slide.title)}"><div class="preview-slide"><header><span>${slide.deliverable==="appendix"?"ANEXĂ":"RAPORT PRINCIPAL"} · PREVIZUALIZARE</span><strong>${esc(slide.title)}</strong></header>${slideBody(slide,payload)}<footer>${slide.number} / ${plan.length}</footer></div></div><div class="preview-controls"><button type="button" data-action="previous" ${selected===0?"disabled":""}>← Anterior</button><span>Slide ${slide.number} din ${plan.length}</span><button type="button" data-action="next" ${selected===plan.length-1?"disabled":""}>Următor →</button></div></section></div>`;root.querySelectorAll("[data-slide],[data-section]").forEach(button=>button.addEventListener("click",()=>{selected=Number(button.dataset.slide??button.dataset.section);render();}));root.querySelector("[data-action=previous]")?.addEventListener("click",()=>{selected--;render();});root.querySelector("[data-action=next]")?.addEventListener("click",()=>{selected++;render();});root.querySelector(".preview-stage").addEventListener("keydown",event=>{if(event.key==="ArrowLeft"&&selected){event.preventDefault();selected--;render();}if(event.key==="ArrowRight"&&selected<plan.length-1){event.preventDefault();selected++;render();}});};if(plan.length)render();return plan;}
