import assert from "node:assert/strict";
import { readFile, writeFile, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import test from "node:test";
import { buildPayload, createAuditWorkbook, mergeSelectedFiles } from "../src/core.js";
const root=resolve(dirname(fileURLToPath(import.meta.url)),".."); const vendor=await readFile(resolve(root,"src/assets/vendor/xlsx.full.min.js"),"utf8"); const sandbox={exports:{},module:{exports:{}},Buffer,process}; vm.runInNewContext(vendor,sandbox); const XLSX=sandbox.exports;
function workbook(rows){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),"Simple");return XLSX.write(wb,{type:"buffer",bookType:"xlsx"})}
const summary=workbook([["code","name","Job","Email","cod cp","People Management","Colaborare"],["","D210 Ana","","","A-1",4,3],["","D210 Bogdan","","","A-2",2,5]]);
const detailed=workbook([["code","name the person evaluated","Job","Email","cod ac","Competente","People Management","","Colaborare",""],["","","","","","Subcompetente","PM","","Col",""],["","","","","","behavior","b1","b2","b3","b4"],["","D210 Ana","","","A-1","",2,0,1,2],["","D210 Bogdan","","","A-2","",0,2,2,2]]);
test("AC summary and detailed shapes normalize to one payload",()=>{const payload=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary},{name:"detail.xlsx",bytes:detailed}],{projectName:"D210 Test"});assert.equal(payload.readiness,true);assert.equal(payload.records.length,2);assert.equal(payload.calculations[0].mean,3);assert.equal(payload.calculations[1].mean,4);assert.equal(payload.sourceShape.detailed,1)});
test("zero stays observed while blank is explicitly warned",()=>{const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary},{name:"detail.xlsx",bytes:detailed}],{projectName:"D210 Test"});const zero=p.records[0].scores["People Management"];assert.equal(zero,4);assert(p.warnings.some(w=>w.code==="detailed-blank")===false)});
test("stable person-plus-assessment duplicate blocks output",()=>{const dup=workbook([["code","name","cod cp","People Management"],["","D210 Ana","A-1",4],["","D210 Ana","A-1",3]]);const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:dup}],{projectName:"D210 Test"});assert.equal(p.readiness,false);assert(p.blockers.some(b=>b.code==="duplicate-identity"))});
test("sequential file selections accumulate and same-name reselection replaces",()=>{const first={name:"summary.xlsx",bytes:new Uint8Array([1])};const second={name:"detailed.xlsx",bytes:new Uint8Array([2])};const replacement={name:"SUMMARY.xlsx",bytes:new Uint8Array([3])};const accumulated=mergeSelectedFiles(mergeSelectedFiles([], [first]), [second]);assert.deepEqual(accumulated,[first,second]);assert.deepEqual(mergeSelectedFiles(accumulated,[replacement]),[replacement,second])});
test("calculations include the median",()=>{const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary}],{projectName:"D210 Test"});assert.equal(p.calculations[0].median,3);assert.equal(p.calculations[1].median,4)});
test("detailed values produce behavior aggregates and full behavior text",()=>{const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary},{name:"detail.xlsx",bytes:detailed}],{projectName:"D210 Test"});assert.equal(p.behaviorAggregates.length,4);assert.equal(p.behaviorAggregates[0].n,2);assert(p.behaviorAggregates.every(item=>item.behavior.length>0))});
test("canonical Devplan descriptor headers join normalized competency and behavior keys",()=>{const descriptors=workbook([["competency","subcompetency","behavior","objective_text_score_0","objective_text_score_-1","objective_text_score_1","objective_text_score_2"],["people management","","b1","Dezvoltă pasul următor","","","Consolidează practica bună"],["People Management","","b2","Dezvoltă feedbackul","","","Păstrează claritatea"],["Colaborare","","b3","Recuperează alinierea","","","Menține cooperarea"],["Colaborare","","b4","Construiește cooperarea","","","Susține echipa"]]);const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary},{name:"detail.xlsx",bytes:detailed},{name:"devplan.xlsx",bytes:descriptors}],{projectName:"D210 Test",benchmarkLow:"2.5",benchmarkHigh:"3.75"});const b1=p.behaviorAggregates.find(item=>item.behavior==="b1");assert.equal(p.readiness,true);assert.equal(b1.score0,"Dezvoltă pasul următor");assert.equal(b1.score2,"Consolidează practica bună");assert.equal(p.bands.low,2.5);assert.equal(p.bands.high,3.75);});
test("incomplete Devplan coverage blocks instead of falling back to behavior text",()=>{const descriptors=workbook([["Competency","Behavior","Score 0","Score 2"],["People Management","b1","a","b"]]);const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary},{name:"detail.xlsx",bytes:detailed},{name:"devplan.xlsx",bytes:descriptors}],{projectName:"D210 Test"});assert.equal(p.readiness,false);assert(p.blockers.some(item=>item.code==="descriptor-missing"));});
test("duplicate Devplan descriptor blocks release and CODE is retained only as readiness evidence",()=>{const duplicate=workbook([["Competency","Behavior","Score 0","Score 2"],["People Management","b1","a","b"],["people management","B1","c","d"]]);const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary},{name:"devplan.xlsx",bytes:duplicate}],{projectName:"D210 Test"});assert.equal(p.readiness,false);assert(p.blockers.some(item=>item.code==="descriptor-duplicate"));assert.equal(p.codeReadiness.blank,2);});
test("audit workbook preserves calculation and behavior tables",async()=>{const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary},{name:"detail.xlsx",bytes:detailed}],{projectName:"D210 Test"});const dir=await mkdtemp(join(tmpdir(),"grf-d210-"));const xlsx=join(dir,"audit.xlsx");await writeFile(xlsx,XLSX.write(createAuditWorkbook(XLSX,p),{type:"buffer",bookType:"xlsx"}));const reopened=XLSX.read(await readFile(xlsx),{type:"buffer"});assert(reopened.SheetNames.includes("Calcule"));assert(reopened.SheetNames.includes("Comportamente"));assert(reopened.SheetNames.includes("Distribuție"));await rm(dir,{recursive:true,force:true})});
test("unrated participants warn and stay out of arithmetic",()=>{const unrated=workbook([["code","name","cod cp","People Management"],["","D210 Ana","A-1",4],["","D210 Bogdan","A-2",""]]);const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:unrated}],{projectName:"D210 Test"});assert.equal(p.readiness,true);assert.equal(p.participantCounts.total,2);assert.equal(p.participantCounts.included,1);assert.equal(p.participantCounts.excludedUnrated,1);assert.equal(p.records.length,1);assert.equal(p.auditRecords.length,2);assert.equal(p.calculations[0].n,1);assert.equal(p.calculations[0].mean,4);assert(p.warnings.some(w=>w.code==="summary-unrated"))});
test("in-memory corrections resolve issues and recalculate the audit payload",()=>{const unrated=workbook([["code","name","cod cp","People Management"],["","D210 Ana","A-1",""]]);const summaryKey="summary:summary.xlsx:2:People Management";const summaryPayload=buildPayload(XLSX,[{name:"summary.xlsx",bytes:unrated}],{projectName:"D210 Test"},{values:{[summaryKey]:{mode:"value",value:5,sourceName:"summary.xlsx",rowNumber:2,field:"People Management",originalValue:""}}});assert.equal(summaryPayload.warnings.some(item=>item.code==="summary-unrated"),false);assert.equal(summaryPayload.records[0].scores["People Management"],5);assert.equal(summaryPayload.calculations[0].mean,5);assert.equal(summaryPayload.corrections.length,1);const blankDetail=workbook([["code","name the person evaluated","cod ac","Competente","People Management"],["","","","Subcompetente","PM"],["","","","behavior","b1"],["","D210 Ana","A-1","",""]]);const detailKey="detailed:detail.xlsx:4:People Management:b1";const detailPayload=buildPayload(XLSX,[{name:"summary.xlsx",bytes:workbook([["code","name","cod cp","People Management"],["","D210 Ana","A-1",4]])},{name:"detail.xlsx",bytes:blankDetail}],{projectName:"D210 Test"},{values:{[detailKey]:{mode:"value",value:2,sourceName:"detail.xlsx",rowNumber:4,field:"b1",originalValue:""}}});assert.equal(detailPayload.warnings.some(item=>item.code==="detailed-blank"),false);assert.equal(detailPayload.behaviorAggregates[0].n,1);assert.equal(detailPayload.behaviorAggregates[0].pct2,1);});

test("summary detection accepts arbitrary competency names without a People Management dependency",()=>{const generic=workbook([["code","name","cod cp","Gândire sistemică","Curaj managerial"],["","D210 Ana","A-1",4,3]]);const p=buildPayload(XLSX,[{name:"generic-summary.xlsx",bytes:generic}],{projectName:"D210 Test"});assert.equal(p.readiness,true);assert.equal(p.calculations.map(item=>item.competency).join("|"),"Gândire sistemică|Curaj managerial");assert.equal(p.calculations[0].mean,4);});

test("duplicate and detailed-only person-plus-assessment identities block and never enter behavior aggregates",()=>{const identityDetail=workbook([["code","name the person evaluated","cod ac","Competente","People Management"],["","","","Subcompetente","PM"],["","","","behavior","b1"],["","D210 Ana","A-1","",2],["","D210 Ana","A-1","",0],["","D210 Extra","X-9","",2]]);const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary},{name:"identity-detail.xlsx",bytes:identityDetail}],{projectName:"D210 Test"});const duplicate=p.blockers.find(item=>item.code==="detailed-duplicate-identity"),orphan=p.blockers.find(item=>item.code==="detailed-only-identity");assert.equal(p.readiness,false);assert(duplicate&&duplicate.sourceName==="identity-detail.xlsx"&&duplicate.identity.includes("d210 ana|a-1"));assert(orphan&&orphan.message.includes("D210 Extra + X-9")&&orphan.sourceName==="identity-detail.xlsx");assert.equal(p.behaviorAggregates.length,0,"duplicate and detailed-only rows cannot double-count the group");assert(p.warnings.some(item=>item.code==="detailed-missing-identity"&&item.identity.includes("d210 bogdan|a-2")));});

test("differently named competing authoritative sources block with deterministic recovery details",()=>{const p=buildPayload(XLSX,[{name:"summary-old.xlsx",bytes:summary},{name:"summary-new.xlsx",bytes:summary}],{projectName:"D210 Test"});const blocker=p.blockers.find(item=>item.code==="summary-source-ambiguity");assert.equal(p.readiness,false);assert(blocker.message.includes("summary-old.xlsx, summary-new.xlsx"));assert.match(blocker.message,/Niciunul nu este ales automat/);assert.match(blocker.message,/Șterge sesiunea/);assert.equal(p.sourceShape.summary,2);});

test("duplicate normalized Devplan keys across files block without last-file-wins",()=>{const oneSummary=workbook([["code","name","cod cp","Leadership"],["","D210 Ana","A-1",4]]),oneDetail=workbook([["code","name the person evaluated","cod ac","Competente","Leadership"],["","","","Subcompetente","L"],["","","","behavior","b1"],["","D210 Ana","A-1","",2]]),first=workbook([["Competency","Behavior","Score 0","Score 2"],["Leadership","b1","Prima dezvoltare","Prima consolidare"]]),second=workbook([["Competency","Behavior","Score 0","Score 2"],[" leadership ","B1","A doua dezvoltare","A doua consolidare"]]);const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:oneSummary},{name:"detail.xlsx",bytes:oneDetail},{name:"devplan-a.xlsx",bytes:first},{name:"devplan-b.xlsx",bytes:second}],{projectName:"D210 Test"});const blocker=p.blockers.find(item=>item.code==="descriptor-duplicate");assert.equal(p.readiness,false);assert(blocker.message.includes("devplan-a.xlsx, rând 2")&&blocker.message.includes("devplan-b.xlsx, rând 2"));assert.equal(p.behaviorAggregates[0].score0,"Prima dezvoltare");assert.equal(p.behaviorAggregates[0].descriptorSource,"devplan-a.xlsx");});

test("fractional detailed scores block visibly and are not coerced into aggregates",()=>{const oneSummary=workbook([["code","name","cod cp","Leadership"],["","D210 Ana","A-1",4]]),fractional=workbook([["code","name the person evaluated","cod ac","Competente","Leadership"],["","","","Subcompetente","L"],["","","","behavior","b1"],["","D210 Ana","A-1","",1.5]]);const p=buildPayload(XLSX,[{name:"summary.xlsx",bytes:oneSummary},{name:"fractional-detail.xlsx",bytes:fractional}],{projectName:"D210 Test"});const blocker=p.blockers.find(item=>item.code==="detailed-score");assert.equal(p.readiness,false);assert.match(blocker.message,/valorile întregi 0, 1 sau 2/);assert.equal(p.behaviorAggregates.length,0);});

test("warning identities and reviewed state survive into the payload and XLSX validation sheet",()=>{const initial=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary}],{projectName:"D210 Test"});assert(initial.warningReviews.length>0);assert(initial.warningReviews.every(item=>item.warningId&&item.reviewed===false));const reviewedIds=initial.warningReviews.map(item=>item.warningId),reviewed=buildPayload(XLSX,[{name:"summary.xlsx",bytes:summary}],{projectName:"D210 Test"},{},{acknowledgedWarningIds:reviewedIds});assert(reviewed.warnings.every(item=>item.reviewed===true));assert(reviewed.warningReviews.every(item=>item.reviewed===true));const wb=createAuditWorkbook(XLSX,reviewed),rows=XLSX.utils.sheet_to_json(wb.Sheets["Validare"],{header:1,defval:""}),header=rows[0],warningRow=rows.find((row,index)=>index>0&&row[0]==="warning");assert.equal(header.slice(0,9).join("|"),"Severitate|Cod|ID avertisment|Revizuit|Sursă|Rând|Identitate stabilă|Câmp|Mesaj");assert.equal(warningRow[2],reviewed.warningReviews[0].warningId);assert.equal(warningRow[3],"Da");});
