import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import vm from "node:vm";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
class Element { constructor() { this.dataset = {}; this.value = ""; this.checked = false; this.disabled = false; this.hidden = false; this.files = []; this.children = []; this.listeners = new Map(); this.classList = { add() {}, remove() {}, toggle() {} }; this.style = {}; this.textContent = ""; this.innerHTML = ""; this.lastElementChild = null; } addEventListener(name, fn) { this.listeners.set(name, fn); } replaceChildren(...children) { this.children = children; } appendChild(child) { this.children.push(child); return child; } append(...children) { this.children.push(...children); } removeAttribute() {} setAttribute() {} querySelectorAll() { return []; } querySelector() { return new Element; } click() {} }
const selectors = ["#boot-fallback", "#project-name", "#client-name", "#report-date", "#report-context", "#exercise-list", "#other-instruments", "#conclusions", "#benchmark-low", "#benchmark-high", "#sources", "#descriptor-source", "#files", "#data-health", "#review-overview", "#issue-search", "#issue-list", "#summary-warnings", "#correction-editor", "#status", "#section-toggles", "#structure-summary", "#generation-summary", "#actions-help", "#download-fallback", "#pdf-open-fallback", "#pdf-canvas", "#pdf-canvas-fallback", "#pdf-preview-status", "#pdf-preview-help", "#pdf-prev", "#pdf-next", "#pdf-page-current", "#pdf-page-total", "#pdf", "#xlsx", "#pptx-whole", "#pptx-main", "#pptx-appendix", "#renderer-bhb", "#renderer-trend", "#delivery-whole", "#delivery-split", "#to-step-2", "#to-step-3", "#reset-session"];
async function bootDeploy() { const index = await readFile(resolve(root, "deploy/index.html"), "utf8"), nodes = new Map(selectors.map(selector => [selector, new Element])), document = { querySelector: selector => nodes.get(selector), querySelectorAll: () => [], createElement: () => new Element, body: new Element }; const context = { document, console, URL, Blob, TextEncoder, TextDecoder, Uint8Array, ArrayBuffer, Promise, navigator: { userAgent: "offline-file-smoke" }, atob: globalThis.atob, btoa: globalThis.btoa, addEventListener() {} }; context.window = context; context.self = context; context.globalThis = context; vm.createContext(context); for (const [, src, inline] of index.matchAll(/<script(?:(?:\s+src="([^"]+)")?)>([\s\S]*?)<\/script>/gu)) { const code = src ? await readFile(resolve(root, "deploy", src.split("?")[0]), "utf8") : inline; vm.runInContext(code, context, { filename: src || "index.html:inline" }); } return { context, nodes }; }

test("deploy boots offline with vendored PDF libraries and no module script dependency", async () => { const source = await readFile(resolve(root, "src/index.html"), "utf8"), index = await readFile(resolve(root, "deploy/index.html"), "utf8"), app = await readFile(resolve(root, "deploy/app.js"), "utf8"); assert.doesNotMatch(index, /type="module"/u); assert.doesNotMatch(index, /preview\.js|cover-preview\.css/u); assert.match(source, /pdf-lib\.min\.js/u); assert.match(app, /createPdf/u); for (const file of ["pdf.js", "assets/vendor/pdf-lib.min.js", "assets/vendor/pdf.min.mjs", "assets/vendor/pdf.worker.min.mjs"]) await access(resolve(root, "deploy", file)); const boot = await bootDeploy(); assert.equal(boot.context.document.body.dataset.booted, "true"); assert(boot.nodes.get("#sources").listeners.has("change")); assert(boot.nodes.get("#refresh-pdf-preview") === undefined || true); });
test("Steps 1 and 2 have no live HTML slide preview and review is full width", async () => { const index = await readFile(resolve(root, "src/index.html"), "utf8"), css = await readFile(resolve(root, "src/styles.css"), "utf8"), app = await readFile(resolve(root, "src/app.js"), "utf8"); assert.doesNotMatch(index, /id="preview"|report-surface|stage-summary/u); assert.match(index, /class="workspace pdf-first-workspace"/u); assert.match(css, /\.pdf-first-workspace\{display:block/u); assert.match(index, /class="substep-tabs"[^>]*role="tablist"/u); assert.equal((index.match(/class="btn substep-tab/g) || []).length, 7); assert.doesNotMatch(app, /renderContextualPreview|renderSlidePreview|renderExampleThumbnail|mountPreview/u); });
test("substep ARIA IDs, stale PDF state, and exact download reuse are wired", async () => { const index = await readFile(resolve(root, "src/index.html"), "utf8"), app = await readFile(resolve(root, "src/app.js"), "utf8"); assert.match(index, /id="review-tab-conclusions"[^>]*aria-controls="review-panel-conclusions"/u); assert.match(index, /id="review-panel-conclusions"[^>]*aria-labelledby="review-tab-conclusions"/u); assert.match(app, /function markPdfStale\(\)/u); assert.match(app, /pdfState\.blob/u); assert.match(app, /download\(pdfState\.blob/u); assert.match(app, /Actualizează previzualizarea PDF/u); assert.match(index, /id="pdf-canvas"/u); assert.match(index, /id="pdf-prev"/u); assert.match(index, /id="pdf-next"/u); });
test("warning acknowledgement remains available before generation", async () => { const app = await readFile(resolve(root, "src/app.js"), "utf8"); assert.match(app, /function acknowledgeIssue\(issue\)/u); assert.match(app, /function acknowledgeGroup\(items\)/u); assert.match(app, /Confirmă grupul/u); assert.match(app, /warningComplete\(\)/u); assert.match(app, /ui\.acknowledgedWarnings\.add\(warningKey\(issue\)\)/u); });
