import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import vm from "node:vm";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
class Element{constructor(){this.dataset={};this.value="";this.checked=false;this.disabled=false;this.hidden=false;this.files=[];this.children=[];this.listeners=new Map();this.style={};this.classList={add(){},remove(){}};this.textContent="";this.innerHTML="";}addEventListener(name,handler){this.listeners.set(name,handler);}replaceChildren(...children){this.children=children;}appendChild(child){this.children.push(child);return child;}append(child){return this.appendChild(child);}remove(){}removeAttribute(name){delete this[name];}setAttribute(name,value){this[name]=value;}getAttribute(name){return this[name]??null;}querySelectorAll(){return [];}querySelector(){return new Element();}click(){}}
const selectors=["#boot-fallback","#project-name","#client-name","#report-date","#report-context","#exercise-list","#other-instruments","#conclusions","#benchmark-low","#benchmark-high","#sources","#files","#messages","#warning-actions","#review-overview","#issue-search","#issue-list","#correction-editor","#status","#metrics","#preview","#stage-summary","#structure-summary","#generation-summary","#actions-help","#download-fallback","#xlsx","#pptx-whole","#pptx-main","#pptx-appendix","#renderer-bhb","#renderer-trend","#delivery-whole","#delivery-split","#to-step-2","#to-step-3","#to-step-4","#reset"];
const browserContext=()=>{const nodes=new Map(selectors.map(selector=>[selector,new Element()]));nodes.get("#boot-fallback").lastElementChild=new Element();const document={querySelector:selector=>nodes.get(selector),querySelectorAll:()=>[],createElement:()=>new Element(),createElementNS:()=>new Element(),getElementById:()=>null,body:new Element()};const context={document,console,URL,Blob,setTimeout,clearTimeout,TextEncoder,TextDecoder,Uint8Array,Uint16Array,Uint32Array,ArrayBuffer,Promise,navigator:{userAgent:"offline-file-smoke"},atob:globalThis.atob,btoa:globalThis.btoa,addEventListener(){}};context.window=context;context.self=context;context.globalThis=context;return{context,nodes};};
async function bootDeploy(){const index=await readFile(resolve(root,"deploy/index.html"),"utf8"),scripts=[...index.matchAll(/<script(?:(?:\s+src="([^"]+)")?)>([\s\S]*?)<\/script>/gu)],{context,nodes}=browserContext();vm.createContext(context);for(const [,src,inline] of scripts){const code=src?await readFile(resolve(root,"deploy",src.split("?")[0]),"utf8"):inline;vm.runInContext(code,context,{filename:src||"deploy/index.html:inline"});}return{context,nodes};}
test("deploy boots through the exact file:// script graph",async()=>{const sourceIndex=await readFile(resolve(root,"src/index.html"),"utf8"),index=await readFile(resolve(root,"deploy/index.html"),"utf8"),script=await readFile(resolve(root,"deploy/app.js"),"utf8"),css=await readFile(resolve(root,"deploy/styles.css"),"utf8");assert.match(sourceIndex,/location\.replace\("\.\.\/deploy\/index\.html"\)/u,"the source entry redirects to the runnable deploy");assert.doesNotMatch(index,/location\.replace\("\.\.\/deploy\/index\.html"\)/u,"the generated deploy entry has no source-only redirect");assert.match(index,/Cache-Control/u);assert.match(index,/styles\.css\?v=/u);assert(css.length>7000,"deploy includes the complete application stylesheet");assert.match(css,/\.workspace\{/u);assert.match(css,/body\[data-booted="true"\] #boot-fallback/u,"successful bootstrap hides the fallback banner");assert.doesNotMatch(index,/type="module"/u);assert.doesNotMatch(script,/^import /mu);const scripts=[...index.matchAll(/<script(?:(?:\s+src="([^"]+)")?)>([\s\S]*?)<\/script>/gu)];assert.equal(scripts.length,6,"deploy keeps the complete classic browser script order plus bootstrap fallback");const {context,nodes}=browserContext();vm.createContext(context);for(const [,src,inline] of scripts){if(src){const local=resolve(root,"deploy",src.split("?")[0]);await access(local);const code=await readFile(local,"utf8");assert.doesNotThrow(()=>vm.runInContext(code,context,{filename:local}));}else assert.doesNotThrow(()=>vm.runInContext(inline,context,{filename:"deploy/index.html:inline"}));}assert.equal(typeof context.XLSX,"object","XLSX bundle attaches to the browser global");assert.equal(typeof context.JSZip,"function","JSZip bundle attaches to the browser global");assert.equal(typeof context.PptxGenJS,"function","PptxGenJS bundle attaches to the browser global");assert.equal(context.document.body.dataset.booted,"true","the app hides the visible fallback only after a successful bootstrap");assert.match(nodes.get("#preview").innerHTML,/Încarcă exporturile complete/);assert(nodes.get("#sources").listeners.has("change"));assert(nodes.get("#pptx-whole").listeners.has("click"));});

test("deploy presents a grouped repair workspace with in-context correction controls",async()=>{const index=await readFile(resolve(root,"deploy/index.html"),"utf8"),css=await readFile(resolve(root,"deploy/styles.css"),"utf8"),script=await readFile(resolve(root,"deploy/app.js"),"utf8");assert.match(css,/\.authoring\{position:static;max-height:none;overflow:visible\}/u,"the authoring panel no longer owns a nested viewport");assert.match(css,/#messages,#warning-actions\{display:none!important\}/u,"the duplicate validation feeds are removed from the operator view");assert.match(css,/\.issue-group\{/u,"issues are presented as grouped repair cards");assert.match(index,/id="issue-list"/u,"the verification step has a repair queue");assert.match(index,/id="correction-editor"/u,"the verification step has an in-context correction editor");assert.match(script,/buildPayload\(window\.XLSX,files,metadata\(\),ui\.corrections,\{acknowledgedWarningIds:/u,"corrections and warning review feed the same normalized payload");assert.match(script,/Salvează și recalculează/u,"the correction action recalculates the report");assert.match(index,/data-step="4"/u,"the workflow includes the export step");assert.match(index,/id="actions-help"/u,"download readiness is explained beside the action buttons");assert.match(index,/id="pptx-main"/u,"the split main-report action is present");assert.match(script,/pptx-whole/u,"the output actions are wired");});

test("deploy provides a visible download recovery link",async()=>{const index=await readFile(resolve(root,"deploy/index.html"),"utf8"),app=await readFile(resolve(root,"deploy/app.js"),"utf8"),pptx=await readFile(resolve(root,"deploy/pptx.js"),"utf8");assert.match(index,/id="download-fallback"/u,"the action area includes a manual download fallback");assert.match(app,/reportDownloadError/u,"export errors are surfaced in the action area");assert.match(app,/window\.__grfDownload=download/u,"PPTX and XLSX share the same browser download helper");assert.match(app,/link\.click\(\)/u,"the attached fallback link is triggered from the button action");assert.match(pptx,/window\.__grfDownload/u,"PPTX uses the shared download helper when the app is running");});

test("deployed replacement, reset and reload paths stay fresh and escape hostile workbook headers",async()=>{const first=await bootDeploy(),hostile='<img src=x onerror="globalThis.__grfOwned=1">';first.nodes.get("#project-name").value="D210 Test";const makeBytes=score=>{const wb=first.context.XLSX.utils.book_new();first.context.XLSX.utils.book_append_sheet(wb,first.context.XLSX.utils.aoa_to_sheet([["code","name","cod cp",hostile],["","D210 Ana","A-1",score]]),"Simple");return first.context.XLSX.write(wb,{type:"array",bookType:"xlsx"});},select=async bytes=>first.nodes.get("#sources").listeners.get("change")({target:{files:[{name:"summary.xlsx",arrayBuffer:async()=>new Uint8Array(bytes).buffer}],value:"selected"}});await select(makeBytes(4));let article=first.nodes.get("#metrics").children[0];assert.equal(article.children[0].textContent,"4.00");assert.equal(article.children[1].textContent,hostile);assert.equal(article.innerHTML,"");assert.doesNotMatch(first.nodes.get("#preview").innerHTML,/<img src=x/iu);await select(makeBytes(2));article=first.nodes.get("#metrics").children[0];assert.equal(article.children[0].textContent,"2.00","same-name replacement recalculates from the replacement source");first.nodes.get("#reset").listeners.get("click")();assert.equal(first.nodes.get("#files").textContent,"Niciun fișier selectat");assert.equal(first.nodes.get("#metrics").children.length,0);assert.equal(first.context.document.body.dataset.workflowStep,"1");const reloaded=await bootDeploy();assert.equal(reloaded.nodes.get("#files").textContent,"Niciun fișier selectat");assert.equal(reloaded.nodes.get("#metrics").children.length,0);assert.equal(reloaded.context.__grfOwned,undefined);});
