import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import vm from "node:vm";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
class Element {
  constructor() { this.dataset = {}; this.value = ""; this.checked = false; this.disabled = false; this.hidden = false; this.files = []; this.children = []; this.listeners = new Map(); this.style = {}; this.classList = { add() {}, remove() {}, toggle() {} }; this.textContent = ""; this.innerHTML = ""; }
  addEventListener(name, handler) { this.listeners.set(name, handler); }
  replaceChildren(...children) { this.children = children; }
  appendChild(child) { this.children.push(child); return child; }
  append(...children) { this.children.push(...children); }
  remove() {}
  removeAttribute(name) { delete this[name]; }
  setAttribute(name, value) { this[name] = value; }
  getAttribute(name) { return this[name] ?? null; }
  querySelectorAll() { return []; }
  querySelector() { return new Element(); }
  click() {}
}
const selectors = ["#boot-fallback", "#project-name", "#client-name", "#report-date", "#report-context", "#exercise-list", "#other-instruments", "#conclusions", "#benchmark-low", "#benchmark-high", "#sources", "#descriptor-source", "#files", "#review-overview", "#issue-search", "#issue-list", "#summary-warnings", "#correction-editor", "#status", "#preview", "#stage-summary", "#section-toggles", "#structure-summary", "#generation-summary", "#actions-help", "#download-fallback", "#xlsx", "#pptx-whole", "#pptx-main", "#pptx-appendix", "#renderer-bhb", "#renderer-trend", "#delivery-whole", "#delivery-split", "#to-step-2", "#to-step-3", "#reset", "#reset-session"];
const browserContext = () => { const nodes = new Map(selectors.map(selector => [selector, new Element()])); nodes.get("#boot-fallback").lastElementChild = new Element(); const document = { querySelector: selector => nodes.get(selector), querySelectorAll: () => [], createElement: () => new Element(), createElementNS: () => new Element(), getElementById: () => null, body: new Element() }; const context = { document, console, URL, Blob, setTimeout, clearTimeout, TextEncoder, TextDecoder, Uint8Array, Uint16Array, Uint32Array, ArrayBuffer, Promise, navigator: { userAgent: "offline-file-smoke" }, atob: globalThis.atob, btoa: globalThis.btoa, addEventListener() {} }; context.window = context; context.self = context; context.globalThis = context; return { context, nodes }; };
async function bootDeploy() { const index = await readFile(resolve(root, "deploy/index.html"), "utf8"), scripts = [...index.matchAll(/<script(?:(?:\s+src="([^"]+)")?)>([\s\S]*?)<\/script>/gu)], { context, nodes } = browserContext(); vm.createContext(context); for (const [, src, inline] of scripts) { const code = src ? await readFile(resolve(root, "deploy", src.split("?")[0]), "utf8") : inline; vm.runInContext(code, context, { filename: src || "deploy/index.html:inline" }); } return { context, nodes }; }

test("deploy boots through the exact file:// script graph", async () => { const sourceIndex = await readFile(resolve(root, "src/index.html"), "utf8"), index = await readFile(resolve(root, "deploy/index.html"), "utf8"), script = await readFile(resolve(root, "deploy/app.js"), "utf8"), css = await readFile(resolve(root, "deploy/styles.css"), "utf8"); assert.match(sourceIndex, /location\.replace\("\.\.\/deploy\/index\.html"\)/u); assert.doesNotMatch(index, /location\.replace\("\.\.\/deploy\/index\.html"\)/u); assert.match(index, /Cache-Control/u); assert.match(index, /styles\.css\?v=/u); assert(css.length > 7000); assert.match(css, /\.workspace\{/u); assert.match(css, /body\[data-booted="true"\] #boot-fallback/u); assert.doesNotMatch(index, /type="module"/u); assert.doesNotMatch(script, /^import /mu); const scripts = [...index.matchAll(/<script(?:(?:\s+src="([^"]+)")?)>([\s\S]*?)<\/script>/gu)]; assert.equal(scripts.length, 6); const { context, nodes } = browserContext(); vm.createContext(context); for (const [, src, inline] of scripts) { if (src) { const local = resolve(root, "deploy", src.split("?")[0]); await access(local); const code = await readFile(local, "utf8"); assert.doesNotThrow(() => vm.runInContext(code, context)); } else assert.doesNotThrow(() => vm.runInContext(inline, context)); } assert.equal(typeof context.XLSX, "object"); assert.equal(typeof context.JSZip, "function"); assert.equal(typeof context.PptxGenJS, "function"); assert.equal(context.document.body.dataset.booted, "true"); assert.match(nodes.get("#preview").innerHTML, /Încarcă exporturile pentru a începe/); assert(nodes.get("#sources").listeners.has("change")); assert(nodes.get("#descriptor-source").listeners.has("change")); assert(nodes.get("#pptx-whole").listeners.has("click")); });

test("deploy presents the three-step review workspace", async () => { const index = await readFile(resolve(root, "deploy/index.html"), "utf8"), css = await readFile(resolve(root, "deploy/styles.css"), "utf8"), script = await readFile(resolve(root, "deploy/app.js"), "utf8"); assert.match(css, /\.authoring\{position:static/); assert.match(css, /\.issue-group\{/u); assert.match(index, /id="dropzone"/u); assert.match(index, /id="issue-list"/u); assert.match(index, /id="correction-editor"/u); assert.match(index, /data-step="3"/u); assert.doesNotMatch(index, /data-step="4"/u); assert.equal((index.match(/class="btn substep-tab(?: active)?"/g) || []).length, 7); assert.match(script, /buildPayload\(window\.XLSX,\s*files,\s*(?:metadata\(\)|meta),\s*ui\.corrections,\s*\{\s*acknowledgedWarningIds\s*:/u); assert.match(script, /refreshMetadata/u); assert.match(script, /Salvează și recalculează/u); assert.match(index, /id="actions-help"/u); assert.match(index, /id="pptx-main"/u); assert.match(script, /pptx-whole/u); });

test("invalidateData keeps the visible substep panel synchronized", async () => { const source = await readFile(resolve(root, "src/app.js"), "utf8"); assert.match(source, /function syncSubstep\(\)/u); assert.match(source, /invalidateData\(\)[\s\S]*?ui\.substep = "data"[\s\S]*?render\(\)/u); assert.match(source, /panel\.hidden = !selected/u); assert.match(source, /render\(\)[\s\S]*?syncSubstep\(\)[\s\S]*?renderContextualPreview\(\)/u); });

test("summary correction moves the editor to the visible data panel", async () => { const source = await readFile(resolve(root, "src/app.js"), "utf8"), index = await readFile(resolve(root, "src/index.html"), "utf8"); assert.match(source, /ui\.substep !== "data"[\s\S]*?syncSubstep\(\)[\s\S]*?renderReview\(\)[\s\S]*?\$\("#correction-value"\)\?\.focus\(\)/u); assert.match(index, /id="correction-editor"[^>]*aria-live="polite"/u); });

test("section toggle rerender restores keyboard focus to its replacement", async () => { const source = await readFile(resolve(root, "src/app.js"), "utf8"); assert.match(source, /const focusKey = document\.activeElement\?\.dataset\?\.sectionKey/u); assert.match(source, /find\(button => button\.dataset\.sectionKey === focusKey\)\?\.focus\(\)/u); });

test("interactive workflow controls retain the shared button contract", async () => { const source = await readFile(resolve(root, "src/app.js"), "utf8"), preview = await readFile(resolve(root, "src/preview.js"), "utf8"), index = await readFile(resolve(root, "src/index.html"), "utf8"); assert.match(source, /className = "btn workflow-step/u); assert.match(source, /class="btn toggle-switch/u); assert.match(index, /class="btn review-filter/u); assert.match(preview, /class="btn btn-ghost btn-sm preview-section-button/u); assert.match(preview, /class="btn btn-ghost btn-sm preview-thumb/u); assert.match(preview, /class="btn btn-ghost btn-sm preview-control/u); });

test("review tabs and section switches expose synchronized ARIA state", async () => { const source = await readFile(resolve(root, "src/app.js"), "utf8"), index = await readFile(resolve(root, "src/index.html"), "utf8"); assert.match(source, /tab\.setAttribute\("role", "tab"\)/u); assert.match(source, /tab\.setAttribute\("aria-selected", String\(selected\)\)/u); assert.match(source, /tab\.setAttribute\("aria-controls", "review-panel-" \+ key\)/u); assert.match(source, /panel\.setAttribute\("role", "tabpanel"\)/u); assert.match(source, /aria-pressed="\$\{isOn && available\}/u); assert.match(index, /role="tab" aria-selected="true" aria-controls="review-panel-data"/u); assert.match(index, /role="tabpanel" aria-labelledby="review-tab-data"/u); });

test("blocked loaded files keep a data-health preview instead of the empty state", async () => { const source = await readFile(resolve(root, "src/app.js"), "utf8"); assert.match(source, /if \(!payload \|\| !files\.length\)[\s\S]*?preview-empty/u); assert.match(source, /if \(!payload\.readiness\) \{ renderDataHealthPreview\(root, payload, files\); return; \}/u); });

test("deploy provides a visible shared download recovery link", async () => { const index = await readFile(resolve(root, "deploy/index.html"), "utf8"), app = await readFile(resolve(root, "deploy/app.js"), "utf8"), pptx = await readFile(resolve(root, "deploy/pptx.js"), "utf8"); assert.match(index, /id="download-fallback"/u); assert.match(app, /reportDownloadError/u); assert.match(app, /window\.__grfDownload\s*=\s*download/u); assert.match(app, /link\.click\(\)/u); assert.match(pptx, /window\.__grfDownload/u); });

test("deployed replacement, reset and reload paths stay fresh and escape hostile workbook headers", async () => { const first = await bootDeploy(), hostile = '<img src=x onerror="globalThis.__grfOwned=1">'; first.nodes.get("#project-name").value = "D210 Test"; const makeBytes = score => { const wb = first.context.XLSX.utils.book_new(); first.context.XLSX.utils.book_append_sheet(wb, first.context.XLSX.utils.aoa_to_sheet([["code", "name", "cod cp", hostile], ["", "D210 Ana", "A-1", score]]), "Simple"); return first.context.XLSX.write(wb, { type: "array", bookType: "xlsx" }); }; const select = async bytes => first.nodes.get("#sources").listeners.get("change")({ target: { files: [{ name: "summary.xlsx", arrayBuffer: async () => new Uint8Array(bytes).buffer }], value: "selected" } }); await select(makeBytes(4)); assert.match(first.nodes.get("#files").textContent, /summary\.xlsx/u); assert.doesNotMatch(first.nodes.get("#preview").innerHTML, /<img src=x/iu); await select(makeBytes(2)); assert.match(first.nodes.get("#files").textContent, /summary\.xlsx/u); first.nodes.get("#reset-session").listeners.get("click")(); assert.equal(first.nodes.get("#files").textContent, "Niciun fișier selectat"); assert.equal(first.context.document.body.dataset.workflowStep, "1"); const reloaded = await bootDeploy(); assert.equal(reloaded.nodes.get("#files").textContent, "Niciun fișier selectat"); assert.equal(reloaded.context.__grfOwned, undefined); });
