// Carried over verbatim from bhb-platform master 40-standalone/group-report-factory/tests/preview.test.mjs (37f9a7e).
// 72655b1 removed that file with preview.js; these four tests cover report-plan.js, which is still live.
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import vm from "node:vm";
import { buildPayload } from "../src/core.js";
import { behaviorInsights, behaviorPageGroups, methodologyColumns, methodologyPages, reportPlan } from "../src/report-plan.js";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");const vendor=await readFile(resolve(root,"src/assets/vendor/xlsx.full.min.js"),"utf8");const sandbox={exports:{},module:{exports:{}},Buffer,process};vm.runInNewContext(vendor,sandbox);const XLSX=sandbox.exports;
function workbook(rows){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),"Simple");return XLSX.write(wb,{type:"buffer",bookType:"xlsx"});}
function fixture(){return buildPayload(XLSX,[{name:"summary.xlsx",bytes:workbook([["code","name","cod cp","People Management","Colaborare"],["","Ana Popescu","A-1",4,3],["","Bogdan Ionescu","A-2",2,5]])},{name:"detail.xlsx",bytes:workbook([["code","name the person evaluated","cod ac","Competente","People Management","Colaborare"],["","","","Subcompetente","PM","COL"],["","","","behavior","Comportament complet pentru prima competență","Comportament complet pentru colaborare"],["","Ana Popescu","A-1","",2,1],["","Bogdan Ionescu","A-2","",0,2]])}],{projectName:"AC test"});}
test("report plan follows metadata and optional conclusion visibility",()=>{const payload=fixture(),without=reportPlan(payload);assert.equal(without.some(slide=>slide.family==="conclusions"),false);payload.metadata.exercises="Simulare de business";payload.metadata.otherInstruments="Interviu structurat";payload.metadata.conclusions="Text aprobat pentru concluzii.";const withMetadata=reportPlan(payload);const methodology=withMetadata.find(slide=>slide.family==="methodology");assert(methodology.page.left.join(" ").includes("Simulare de business"));assert(methodology.page.left.join(" ").includes("Interviu structurat"));assert.equal(withMetadata.some(slide=>slide.family==="conclusions"),true);assert(withMetadata.some(slide=>slide.family==="executive-summary"));assert(withMetadata.some(slide=>slide.family==="key-findings"));assert(withMetadata.some(slide=>slide.family==="appendix-divider"&&slide.deliverable==="appendix"));assert(reportPlan(payload,{scope:"main"}).every(slide=>slide.deliverable==="main"));assert(reportPlan(payload,{scope:"appendix"}).filter(slide=>slide.family!=="close").every(slide=>slide.deliverable==="appendix"));});
test("methodology keeps the canonical compact facts and never inventories dates or locations",()=>{const payload=fixture();payload.schemas=[{methodology:{evaluators:["Consultant 1","Consultant 2"],dates:["2026-06-01","2026-06-02"],locations:["București"],teamSizes:[2,2]}}];const columns=methodologyColumns(payload),copy=[...columns.left,...columns.right].join(" ");assert.match(copy,/2 zile de evaluare organizate/);assert.match(copy,/2 consultanți Trend implicați/);assert.match(copy,/Fiecare participant a fost observat de o echipă de consultanți\./);assert.match(copy,/Platforma a generat rezultatele pentru fiecare competență și rapoartele individuale\./);assert.doesNotMatch(copy,/2026-06|București|Locații\/regiuni/);assert.equal(methodologyPages(payload).length,1);assert.doesNotMatch(copy,/0\s*[–-]\s*1\s*[–-]\s*2/u);});
test("report plan paginates long participants and preserves full selected behavior sentences",()=>{const payload=fixture();payload.records=Array.from({length:19},(_,index)=>({...payload.records[index%2],name:`Participant cu nume foarte lung ${index+1}`,scores:{"People Management":4,"Colaborare":3}}));payload.behaviorAggregates=Array.from({length:9},(_,index)=>({competency:"People Management",behavior:`Comportament ${index+1}: ${"text observabil ".repeat(20)}`,pct0:index/10,pct2:1-index/10,mean:2}));const plan=reportPlan(payload),participantPages=plan.filter(slide=>slide.family==="participant-comparison"),behaviorPages=plan.filter(slide=>slide.family==="behavior"),selected=[...behaviorPages[0].insight.strengths,...behaviorPages[0].insight.development];assert.equal(participantPages.length,4);assert.equal(behaviorPages.length,1);assert(selected.every(item=>payload.behaviorAggregates.some(source=>source.behavior===item.behavior)));assert(selected.every(item=>item.behavior.includes("text observabil")));assert(behaviorPageGroups(payload.behaviorAggregates).every(page=>page.length>0));});
test("behavior insights select deterministic distinct top score-2 and score-0 behaviors",()=>{const rows=[{behavior:"A complet",competency:"Leadership",pct2:.8,pct0:.1,mean:1.8},{behavior:"B complet",competency:"Leadership",pct2:.8,pct0:.05,mean:1.7},{behavior:"C complet",competency:"Leadership",pct2:.6,pct0:.2,mean:1.6},{behavior:"D complet",competency:"Leadership",pct2:.4,pct0:.7,mean:.8},{behavior:"E complet",competency:"Leadership",pct2:.3,pct0:.7,mean:.7},{behavior:"F complet",competency:"Leadership",pct2:.2,pct0:.5,mean:1}];const insight=behaviorInsights(rows)[0];assert.deepEqual(insight.strengths.map(item=>item.behavior),["A complet","B complet","C complet"]);assert.deepEqual(insight.development.map(item=>item.behavior),["E complet","D complet","F complet"]);assert.equal(new Set([...insight.strengths,...insight.development].map(item=>item.behavior)).size,6);const payload=fixture();payload.behaviorAggregates=rows;const behaviorSlides=reportPlan(payload).filter(slide=>slide.family==="behavior");assert.equal(behaviorSlides.length,1);assert.equal(behaviorSlides[0].insight.strengths.map(item=>item.behavior).join(""),"A completB completC complet");});
