import { reportPlan } from "./rebuild-report-plan.js";

const esc=value=>String(value??"").replace(/[&<>"']/gu,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[char]);
const displayTitle=value=>({"Executive Summary":"Rezumat executiv"}[String(value??"")]||String(value??""));
const fixed=value=>Number(value).toFixed(2);
const pct=value=>`${Number(value||0)}%`;
const colors=["#0A375B","#27808F","#4A8C61","#A98138","#64748B","#8B6F47","#5E8197","#71865B"];
function simpleBars(items,value,key="competency"){return `<div class="preview-bars">${items.map((item,index)=>`<div class="preview-bar-item"><span style="height:${Math.max(8,Number(value(item))*18)}%;background:${colors[index%colors.length]}"></span><small>${esc(item[key])}</small><b>${fixed(value(item))}</b></div>`).join("")}</div>`;}
function rangePreview(items){return `<div class="preview-range"><div>${simpleBars(items,item=>item.median)}</div><img src="./assets/images/bhb-range-legend-template.png" alt="Legendă pentru minim, maxim, mediană și benchmark"></div>`;}
function benchmarkPreview(bands){const segments=[[`Mai mică de ${bands.low}`,bands.below,"#003057"],[`Între ${bands.low} – ${bands.high}`,bands.typical,"#a5a5a5"],[`Peste ${bands.high}`,bands.above,"#f8ec32"]];return `<p class="preview-note">Benchmark pe baza evaluărilor Trend: între ${bands.low} și ${bands.high} – performanță la nivel mediu.</p><div class="preview-benchmark" aria-label="Distribuția procentuală a participanților">${segments.map(([label,count,color])=>`<span style="width:${bands.n?count/bands.n*100:0}%;background:${color}"><b>${bands.n?Math.round(count/bands.n*100):0}%</b><small>${esc(label)}</small></span>`).join("")}</div>`;}
function methodologyPreview(slide){const column=(items,missing)=>`<div><h3>${esc(items[0])}</h3><ul>${items.slice(1).map(item=>`<li>${esc(item)}</li>`).join("")}</ul>${missing?`<p class="preview-missing">Completează exercițiile sau alte instrumente numai dacă sunt confirmate.</p>`:""}</div>`;return `<div class="preview-methodology">${column(slide.page.left,slide.page.missing.exercises||slide.page.missing.otherInstruments)}${column(slide.page.right,false)}</div>`;}
function summaryPreview(summary){return `<div class="preview-summary"><div class="summary-stat"><b>${summary.population}</b><span>participanți evaluați</span></div>${summary.distribution.map(item=>`<div class="summary-stat"><b>${pct(item.value)}</b><span>${esc(item.label)}</span></div>`).join("")}</div><div class="summary-copy"><p>${esc(summary.sentence)}</p>${summary.competencyLines.map(line=>`<p>${esc(line)}</p>`).join("")}${summary.conclusions?`<p>${esc(summary.conclusions)}</p>`:`<p class="preview-missing">Concluziile comportamentale rămân de completat de consultant.</p>`}</div>`;}
function listColumn(heading,items){return `<div class="finding-column"><h3>${esc(heading)}</h3>${items.length?items.map((line,index)=>`<article><b>${index+1}</b><span>${esc(line)}</span></article>`).join(""):"<p class=\"preview-missing\">—</p>"}</div>`;}
function findingPreview(slide){return `<div class="finding-score"><b>${fixed(slide.mean)}</b><span>medie · mediană ${fixed(slide.median)} · ${slide.scores.length} participanți (${slide.counts.above} peste · ${slide.counts.in} în · ${slide.counts.below} sub benchmark)</span></div><div class="preview-findings">${listColumn("Abilități cheie – Puncte forte",slide.strengths)}${listColumn("Arii de dezvoltare",slide.development)}</div>`;}
function behaviorPreview(slide){return `<div class="preview-behaviors">${listColumn("Abilități cheie",slide.key)}${listColumn("Abilități de dezvoltat",slide.development)}</div>`;}
function slideBody(slide,payload){
  if(slide.family==="cover")return `<div class="preview-cover"><p>CONFIDENȚIAL</p><h2>${esc(slide.title)}</h2><span>Raport de grup${slide.annexMark?" – Anexă":""} · ${esc(slide.year)}</span></div>`;
  if(slide.family==="how-to-read")return `<div class="summary-copy">${slide.paragraphs.map(text=>`<p>${esc(text)}</p>`).join("")}</div>`;
  if(slide.family==="executive-summary")return summaryPreview(slide.summary);
  if(slide.family.startsWith("divider")||slide.family==="appendix-divider")return `<div class="preview-divider"><h2>${esc(slide.title)}</h2></div>`;
  if(slide.family==="methodology")return methodologyPreview(slide);
  if(slide.family==="range")return rangePreview(slide.items);
  if(slide.family==="ranking")return simpleBars(slide.items.slice().reverse(),item=>item.mean);
  if(slide.family==="benchmark")return benchmarkPreview({...slide.table,low:slide.low,high:slide.high,below:slide.table.counts.below,typical:slide.table.counts.in,above:slide.table.counts.above,n:slide.table.rows.length});
  if(slide.family==="population")return `<table><thead><tr><th>Competență</th><th>Sub</th><th>În</th><th>Peste</th></tr></thead><tbody>${slide.rows.map(row=>`<tr><td>${esc(row.competency)}</td><td>${pct(row.below)}</td><td>${pct(row.in)}</td><td>${pct(row.above)}</td></tr>`).join("")}</tbody></table>`;
  if(slide.family==="zone")return `<table><thead><tr><th>Regiune</th>${slide.competencies.map(name=>`<th>${esc(name)}</th>`).join("")}</tr></thead><tbody>${slide.regions.map((region,index)=>`<tr><td>${esc(region)}</td>${slide.values[index].map(value=>`<td>${value===null?"":fixed(value)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;
  if(slide.family==="key-findings")return findingPreview(slide);
  if(slide.family==="behavior")return behaviorPreview(slide);
  if(slide.family==="conclusions")return `<div class="summary-copy">${[["Abilități cheie",slide.strengths],["Arii de dezvoltare",slide.development],["Posibile intervenții",slide.interventions]].map(([heading,value])=>`<p><b>${heading}:</b> ${value?esc(value):"<span class=\"preview-missing\">de completat de consultant</span>"}</p>`).join("")}</div>`;
  if(slide.family==="participant-mean")return simpleBars(slide.rows,row=>row.mean,"name");
  if(slide.family==="participant-comparison")return `<div class="preview-gridchart">${slide.rows.map(row=>`<div><b>${esc(row.name)}</b>${slide.competencies.map((name,index)=>`<i style="width:${(row.scores[name]||0)*20}%;background:${colors[index%colors.length]}"></i>`).join("")}</div>`).join("")}</div>`;
  if(slide.family==="competency-participants")return simpleBars(slide.rows,row=>row.score,"name");
  return `<div class="preview-close">MULȚUMIM!</div>`;
}
export function mountPreview(root,payload,options={}){const plan=reportPlan(payload,{scope:options.scope||"whole"}),sectionFor=slide=>slide.deliverable==="appendix"?"Anexă":["cover","how-to-read","methodology","executive-summary","key-findings"].includes(slide.family)?"Raport principal":slide.family==="behavior"||slide.family==="divider-behaviors"?"Comportamente cheie":slide.family==="close"||slide.family==="conclusions"||slide.family==="divider-conclusions"?"Concluzii":"Rezultate",sections=[...new Map(plan.map((slide,index)=>[sectionFor(slide),index])).entries()];let selected=Math.min(Number(root.dataset.selected||0),Math.max(0,plan.length-1));const render=()=>{const slide=plan[selected],title=displayTitle(slide.title);root.dataset.selected=String(selected);root.innerHTML=`<div class="preview-heading"><div><p>Previzualizare structură raport</p><h2>Raportul care va fi generat</h2></div><span>${slide.number} / ${plan.length}</span></div><nav class="preview-sections" aria-label="Secțiuni raport">${sections.map(([name,index])=>`<button type="button" data-section="${index}" class="${sectionFor(slide)===name?"selected":""}">${esc(name)}</button>`).join("")}</nav><div class="preview-layout"><nav class="preview-thumbnails" aria-label="Slide-uri raport">${plan.map((item,index)=>`<button type="button" data-slide="${index}" class="${index===selected?"selected":""}" aria-label="Slide ${index+1}: ${esc(displayTitle(item.title))}"><b>${index+1}</b><span>${esc(displayTitle(item.title))}</span>${item.deliverable==="appendix"?`<em>Anexă</em>`:""}</button>`).join("")}</nav><section class="preview-stage-wrap"><div class="preview-stage" tabindex="0" aria-label="Previzualizare slide ${slide.number}: ${esc(title)}"><div class="preview-slide"><header><span>${slide.deliverable==="appendix"?"ANEXĂ":"RAPORT PRINCIPAL"} · PREVIZUALIZARE</span><strong>${esc(title)}</strong></header>${slideBody(slide,payload)}<footer>${slide.number} / ${plan.length}</footer></div></div><div class="preview-controls"><button type="button" data-action="previous" ${selected===0?"disabled":""}>← Anterior</button><span>Slide ${slide.number} din ${plan.length}</span><button type="button" data-action="next" ${selected===plan.length-1?"disabled":""}>Următor →</button></div></section></div>`;root.querySelectorAll("[data-slide],[data-section]").forEach(button=>button.addEventListener("click",()=>{selected=Number(button.dataset.slide??button.dataset.section);render();}));root.querySelector("[data-action=previous]")?.addEventListener("click",()=>{selected--;render();});root.querySelector("[data-action=next]")?.addEventListener("click",()=>{selected++;render();});root.querySelector(".preview-stage").addEventListener("keydown",event=>{if(event.key==="ArrowLeft"&&selected){event.preventDefault();selected--;render();}if(event.key==="ArrowRight"&&selected<plan.length-1){event.preventDefault();selected++;render();}});};if(plan.length)render();return plan;}
