import { buildPayload, createAuditWorkbook, mergeSelectedFiles } from "./core.js";
import { downloadPptx } from "./pptx.js";
import { mountPreview } from "./preview.js";
import { reportPlan } from "./report-plan.js";

if(!window.XLSX||!window.JSZip||!window.PptxGenJS)throw new Error("Lipsesc bibliotecile locale necesare");
let files=[];let payload=null;let activeDownloadUrl="";
const ui={step:1,renderer:"bhb",delivery:"whole",acknowledgedWarnings:new Set(),corrections:{values:{}},reviewFilter:"open",reviewSearch:"",activeIssue:null,activeGroup:"",groupLimits:{},inlineError:"",busy:false,generated:false};
const $=selector=>document.querySelector(selector);
const warningKey=item=>item.id||item.code+":"+(item.rowNumber||"")+":"+item.message;
const issueLabel={"summary-scores":"Lipsesc sau sunt invalide scoruri de competență","detailed-behavior":"Comportamente neobservate sau cu scor invalid","detailed-optional":"Lipsește exportul detaliat","detailed-missing-identity":"Participanți lipsă din exportul detaliat","detailed-identity":"Identități detaliate nealiniate","source-ambiguity":"Mai multe surse pot fi autoritative","descriptor-missing":"Descriptori Devplan incompleți","descriptor-unmatched":"Descriptori fără corespondență","descriptor-duplicate":"Descriptori Devplan duplicați","360-contract":"Fișier 360 recunoscut, dar neimplementat","unsupported":"Fișier nerecunoscut","required-value":"Date obligatorii lipsă","summary-headers":"Structură de fișier nerecunoscută","detailed-headers":"Structură de fișier nerecunoscută","duplicate-identity":"Identitate duplicată","benchmark-invalid":"Benchmark invalid","project-required":"Numele proiectului lipsește"};
const setActionMessage=(message,kind="")=>{const node=$("#actions-help");if(node){node.textContent=message;node.className="actions-help"+(kind?" "+kind:"");}};
const reportDownloadError=error=>{const message=error instanceof Error?error.message:String(error??"eroare necunoscută");setActionMessage("Descărcarea nu a pornit: "+message+". Încearcă din nou după verificarea blocajelor.","download-error");};
const clearDownload=()=>{const link=$("#download-fallback");if(link){link.hidden=true;link.removeAttribute("href");link.removeAttribute("download");link.textContent="";}if(activeDownloadUrl){URL.revokeObjectURL(activeDownloadUrl);activeDownloadUrl="";}};
const download=(blob,name)=>{clearDownload();activeDownloadUrl=URL.createObjectURL(blob);const link=$("#download-fallback");if(!link)throw new Error("Lipsește linkul local de descărcare");link.href=activeDownloadUrl;link.download=name;link.textContent="Dacă descărcarea nu a pornit, apasă aici pentru "+name+".";link.hidden=false;link.click();};
window.__grfDownload=download;
function metadata(){return{projectName:$("#project-name")?.value||"",clientName:$("#client-name")?.value||"",reportDate:$("#report-date")?.value||"",context:$("#report-context")?.value||"",exercises:$("#exercise-list")?.value||"",otherInstruments:$("#other-instruments")?.value||"",conclusions:$("#conclusions")?.value||"",benchmarkLow:$("#benchmark-low")?.value??"2.75",benchmarkHigh:$("#benchmark-high")?.value??"3.5"};}
function allIssues(){return[...(payload?.blockers||[]),...(payload?.warnings||[])];}
function isAcknowledged(issue){return issue.severity==="warning"&&issue.reviewed===true;}
function openIssues(){return allIssues().filter(issue=>!isAcknowledged(issue));}
function warningComplete(){return!!payload&&!payload.warnings.some(item=>!isAcknowledged(item));}
function stepReady(step){if(step===1)return files.length>0;if(step===2)return!!payload&&payload.readiness&&warningComplete();if(step===3)return stepReady(2);if(step===4)return stepReady(3);return false;}
function invalidateData(){ui.generated=false;ui.activeIssue=null;ui.inlineError="";if(ui.step>1)ui.step=1;render();}
function canEnterStep(step){if(step===1)return true;if(step===2)return stepReady(1);return stepReady(step);}
function setStep(step){const next=Number(step);if(next<=ui.step||canEnterStep(next)){ui.step=next;ui.activeIssue=null;ui.inlineError="";syncWorkflow();renderReview();}}
function issueGroupKey(issue){return issue.groupKey||issue.code;}
function visibleIssue(issue){if(ui.reviewFilter==="blockers"&&issue.severity!=="blocker")return false;if(ui.reviewFilter==="warnings"&&issue.severity!=="warning")return false;if(ui.reviewFilter==="resolved"&&!isAcknowledged(issue))return false;if(ui.reviewFilter!=="resolved"&&isAcknowledged(issue))return false;if(!ui.reviewSearch)return true;const haystack=[issue.message,issue.sourceName,issue.field,issue.subject,issue.identity].join(" ").toLocaleLowerCase("ro");return haystack.includes(ui.reviewSearch.toLocaleLowerCase("ro"));}
function isCorrectable(issue){return["summary-unrated","summary-score","detailed-blank","detailed-score"].includes(issue.code)&&!!issue.correctionKey;}
function isFileRecovery(issue){return["unsupported","summary-required","summary-source-ambiguity","detailed-source-ambiguity","detailed-duplicate-identity","detailed-only-identity","detailed-headers","summary-headers","descriptor-headers","descriptor-duplicate","descriptor-missing","descriptor-unmatched","detailed-missing-identity","360-contract"].includes(issue.code);}
function addButton(parent,label,className,handler){const button=document.createElement("button");button.type="button";button.className=className||"btn-ghost btn-sm";button.textContent=label;button.addEventListener("click",handler);parent.appendChild(button);return button;}
function setActiveGroup(groupKey){ui.activeGroup=ui.activeGroup===groupKey?"":groupKey;ui.activeIssue=null;ui.inlineError="";renderReview();}
function acknowledgeIssue(issue){ui.acknowledgedWarnings.add(warningKey(issue));ui.activeIssue=null;ui.inlineError="";render();}
function acknowledgeGroup(items){items.filter(issue=>issue.severity==="warning").forEach(issue=>ui.acknowledgedWarnings.add(warningKey(issue)));ui.activeIssue=null;render();}
function replaceSources(){ui.activeIssue=null;$("#sources")?.click();}
function issueGroups(){const groups=new Map();allIssues().filter(visibleIssue).forEach(issue=>{const key=issueGroupKey(issue);if(!groups.has(key))groups.set(key,{key,items:[],severity:issue.severity});groups.get(key).items.push(issue);});return[...groups.values()];}
function renderReviewOverview(){const root=$("#review-overview");if(!root||!payload)return;const open=openIssues(),blockers=open.filter(issue=>issue.severity==="blocker").length,warnings=open.filter(issue=>issue.severity==="warning").length,resolved=payload.warnings.filter(isAcknowledged).length,corrected=Object.keys(ui.corrections.values||{}).length,attention=blockers+warnings;root.innerHTML="<div class=\"review-state "+(attention?"needs-attention":"all-clear")+"\"><strong>"+(attention?"Necesită atenție":"Totul este pregătit")+"</strong><span>"+(attention?attention+" elemente rămase de rezolvat":"Poți continua la compunerea raportului")+"</span></div><div class=\"review-stats\"><div><b>"+payload.participantCounts.included+"</b><span>incluși în calcule</span></div><div><b>"+payload.participantCounts.excludedUnrated+"</b><span>fără scor, excluși</span></div><div><b>"+blockers+"</b><span>blocaje</span></div><div><b>"+warnings+"</b><span>de verificat</span></div><div><b>"+(resolved+corrected)+"</b><span>rezolvate</span></div></div>";const status=$("#status");if(status){status.textContent=attention?blockers+" blocaje · "+warnings+" avertismente":"Gata de continuare";status.className=attention?"blocked":"ready";}}
function renderReviewFilters(){document.querySelectorAll("[data-review-filter]").forEach(button=>{button.className="review-filter"+(button.dataset.reviewFilter===ui.reviewFilter?" active":"");});}
function renderIssueGroups(){const root=$("#issue-list");if(!root)return;root.replaceChildren();const groups=issueGroups();if(!groups.length){const empty=document.createElement("div");empty.className="review-empty";empty.innerHTML="<strong>Nu mai sunt probleme deschise.</strong><span>Poți continua. Avertismentele păstrate ca atare rămân în audit.</span>";root.appendChild(empty);return;}groups.forEach(group=>{const card=document.createElement("article");card.className="issue-group "+group.severity;const head=document.createElement("div");head.className="issue-group-head";const title=document.createElement("div");title.className="issue-group-title";const kicker=document.createElement("small");kicker.textContent=group.severity==="blocker"?"BLOCAJ":"AVERTISMENT";const heading=document.createElement("h3");heading.textContent=issueLabel[group.key]||group.items[0].message;const count=document.createElement("span");count.className="issue-count";count.textContent=String(group.items.length);title.appendChild(kicker);title.appendChild(heading);title.appendChild(count);head.appendChild(title);const groupActions=document.createElement("div");groupActions.className="issue-group-actions";const expandable=group.items.some(isCorrectable);if(expandable)addButton(groupActions,ui.activeGroup===group.key?"Închide lista":"Deschide lista","btn-ghost btn-sm",()=>setActiveGroup(group.key));if(!expandable&&group.severity==="warning")addButton(groupActions,"Confirmă grupul","btn-ghost btn-sm",()=>acknowledgeGroup(group.items));if(isFileRecovery(group.items[0]))addButton(groupActions,"Înlocuiește fișierul","btn-ghost btn-sm",replaceSources);head.appendChild(groupActions);card.appendChild(head);const summary=document.createElement("p");summary.className="issue-group-summary";summary.textContent=group.items.length===1?group.items[0].message:String(group.items.length)+" elemente din această categorie. Deschide lista pentru a le rezolva pe rând.";card.appendChild(summary);if(ui.activeGroup===group.key&&expandable){const list=document.createElement("div");list.className="issue-items";const limit=ui.groupLimits[group.key]||4;group.items.slice(0,limit).forEach(issue=>{const row=document.createElement("div");row.className="issue-item";const copy=document.createElement("div");copy.className="issue-item-copy";const message=document.createElement("strong");message.textContent=issue.message;const context=document.createElement("small");context.textContent=[issue.sourceName||"",issue.rowNumber?"rând "+issue.rowNumber:"",issue.identity||""].filter(Boolean).join(" · ");copy.appendChild(message);copy.appendChild(context);row.appendChild(copy);addButton(row,"Corectează","btn-aqua btn-sm",()=>{ui.activeIssue=issue;ui.inlineError="";renderReview();});list.appendChild(row);});if(group.items.length>limit)addButton(list,"Arată încă "+(group.items.length-limit),"btn-ghost btn-sm",()=>{ui.groupLimits[group.key]=limit+6;renderReview();});card.appendChild(list);}root.appendChild(card);});}
function renderCorrectionEditor(){const root=$("#correction-editor");if(!root)return;root.replaceChildren();const issue=ui.activeIssue;if(!issue||!isCorrectable(issue)){root.hidden=true;return;}root.hidden=false;const summary=issue.code.startsWith("summary"),title=document.createElement("h3");title.textContent=summary?"Corectează scorul competenței":"Corectează scorul comportamentului";const context=document.createElement("p");context.className="correction-context";context.textContent=[issue.identity,issue.competency||issue.subject,issue.field,issue.sourceName?issue.sourceName+", rând "+issue.rowNumber:""].filter(Boolean).join(" · ");const label=document.createElement("label");label.textContent=summary?"Scor competență (1–5)":"Scor comportament (0–2)";const input=document.createElement("input");input.id="correction-value";input.type="number";input.min=summary?"1":"0";input.max=summary?"5":"2";input.step="1";input.value=issue.originalValue===""?"":String(issue.originalValue);label.appendChild(input);root.appendChild(title);root.appendChild(context);root.appendChild(label);if(ui.inlineError){const error=document.createElement("p");error.className="correction-error";error.textContent=ui.inlineError;root.appendChild(error);}const actions=document.createElement("div");actions.className="correction-actions";addButton(actions,"Salvează și recalculează","btn-aqua",()=>{const value=Number(input.value),min=Number(input.min),max=Number(input.max);if(!Number.isFinite(value)||value<min||value>max||(!summary&&!Number.isInteger(value))){ui.inlineError=summary?"Introdu o valoare între "+min+" și "+max+".":"Introdu una dintre valorile întregi 0, 1 sau 2.";renderCorrectionEditor();return;}ui.corrections.values[issue.correctionKey]={mode:"value",value,sourceName:issue.sourceName,rowNumber:issue.rowNumber,field:issue.field,originalValue:issue.originalValue};ui.activeIssue=null;ui.inlineError="";render();});if(issue.code==="summary-unrated"||issue.code==="detailed-blank")addButton(actions,issue.code==="summary-unrated"?"Păstrează fără scor":"Păstrează neobservat","btn-ghost",()=>acknowledgeIssue(issue));addButton(actions,"Închide","btn-ghost",()=>{ui.activeIssue=null;ui.inlineError="";renderReview();});root.appendChild(actions);}
function renderReview(){renderReviewOverview();renderReviewFilters();renderIssueGroups();renderCorrectionEditor();}
function renderStructure(){const root=$("#structure-summary");if(!root||!payload)return;const plan=reportPlan(payload),main=plan.filter(slide=>slide.deliverable==="main"),appendix=plan.filter(slide=>slide.deliverable==="appendix");root.innerHTML="<div class=\"structure-card\"><strong>Raport principal</strong><span>"+main.length+" slide-uri</span><small>Executive Summary, rezultate, Key Findings, comportamente și concluzii</small></div><div class=\"structure-card\"><strong>Anexă</strong><span>"+appendix.length+" slide-uri</span><small>Distribuții și rezultate individuale detaliate</small></div>";}
function renderGeneration(){const root=$("#generation-summary");if(!root||!payload)return;const plan=reportPlan(payload),main=plan.filter(slide=>slide.deliverable==="main").length,appendix=plan.filter(slide=>slide.deliverable==="appendix").length,renderer=ui.renderer==="trend"?"TREND":"BHB";root.innerHTML="<strong>"+renderer+" · "+(ui.delivery==="whole"?"un singur PPTX":"două livrabile")+"</strong><span>Raport principal: "+main+" slide-uri · Anexă: "+appendix+" slide-uri</span>";}
function syncWorkflow(){document.body.dataset.workflowStep=String(ui.step);document.body.dataset.renderer=ui.renderer;document.querySelectorAll("[data-panel]").forEach(panel=>{panel.hidden=Number(panel.dataset.panel)!==ui.step;});document.querySelectorAll("#workflow-steps [data-step]").forEach(button=>{const step=Number(button.dataset.step);button.className=(step===ui.step?"active ":"")+(step<ui.step?"done":"");button.disabled=step>ui.step&&!canEnterStep(step);});const to2=$("#to-step-2"),to3=$("#to-step-3"),to4=$("#to-step-4");if(to2)to2.disabled=!stepReady(1);if(to3)to3.disabled=!stepReady(2);if(to4)to4.disabled=!stepReady(3);const outputReady=stepReady(4);["#xlsx","#pptx-whole","#pptx-main","#pptx-appendix"].forEach(selector=>{const button=$(selector);if(button)button.disabled=!outputReady||ui.busy;});const whole=$("#pptx-whole"),main=$("#pptx-main"),appendix=$("#pptx-appendix");if(whole)whole.hidden=ui.delivery!=="whole";if(main)main.hidden=ui.delivery!=="split";if(appendix)appendix.hidden=ui.delivery!=="split";renderStructure();renderGeneration();const stage=$("#stage-summary");if(stage){const textByStep={1:"Încarcă fișierele sursă și completează contextul raportului.",2:payload?.blockers.length?"Rezolvă problemele direct aici sau înlocuiește fișierul sursă.":"Verifică elementele rămase și continuă când sunt rezolvate.",3:"Previzualizează raportul principal și anexa, apoi alege rendererul și livrarea.",4:"Livrabilele sunt pregătite pentru generare și descărcare."};stage.textContent=textByStep[ui.step];}}
function render(){payload=buildPayload(window.XLSX,files,metadata(),ui.corrections,{acknowledgedWarningIds:[...ui.acknowledgedWarnings]});Object.assign(payload.metadata,{renderer:ui.renderer,delivery:ui.delivery,exercises:metadata().exercises,otherInstruments:metadata().otherInstruments});const keys=new Set(payload.warnings.map(warningKey));ui.acknowledgedWarnings=new Set([...ui.acknowledgedWarnings].filter(key=>keys.has(key)));$("#files")&&($("#files").textContent=files.length?files.map(file=>file.name).join(" · "):"Niciun fișier selectat");const metrics=$("#metrics");if(metrics)metrics.replaceChildren(...payload.calculations.map(item=>{const article=document.createElement("article"),mean=document.createElement("strong"),competency=document.createElement("span"),details=document.createElement("small");mean.textContent=item.mean?.toFixed(2)??"—";competency.textContent=item.competency;details.textContent="min "+(item.min?.toFixed(2)??"—")+" · mediană "+(item.median?.toFixed(2)??"—")+" · max "+(item.max?.toFixed(2)??"—")+" · n "+item.n;article.appendChild(mean);article.appendChild(competency);article.appendChild(details);return article;}));const preview=$("#preview");if(preview){if(payload.readiness)mountPreview(preview,payload,{scope:"whole"});else{preview.dataset.selected="0";preview.innerHTML="<p class=\"preview-empty\">Încarcă exporturile complete pentru a vedea structura raportului.</p>";}}renderReview();syncWorkflow();}
async function readSources(event){const selected=await Promise.all([...event.target.files].map(async file=>({name:file.name,bytes:await file.arrayBuffer()})));files=mergeSelectedFiles(files,selected);ui.corrections={values:{}};ui.acknowledgedWarnings.clear();event.target.value="";invalidateData();}
function updateChoice(){ui.renderer=$("#renderer-trend")?.checked?"trend":"bhb";ui.delivery=$("#delivery-split")?.checked?"split":"whole";ui.generated=false;render();}
async function createDownload(kind){if(!stepReady(4)||ui.busy)return;ui.busy=true;setActionMessage("Se pregătește livrabilul…");syncWorkflow();const slug=payload.metadata.projectName.replace(/[^a-z0-9]+/giu,"-")||"raport-grup";try{if(kind==="xlsx"){const wb=createAuditWorkbook(window.XLSX,payload),bytes=window.XLSX.write(wb,{type:"array",compression:true,bookType:"xlsx"});download(new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),"audit-raport-grup-"+slug+".xlsx");setActionMessage("Auditul XLSX a fost pregătit pentru descărcare.","ready-help");}else{const scope=kind==="main"?"main":kind==="appendix"?"appendix":"whole",label=scope==="main"?"raport-principal":scope==="appendix"?"anexa":"raport-grup";await downloadPptx(payload,label+"-"+slug+".pptx",{renderer:ui.renderer,scope});setActionMessage("Raportul PPTX a fost pregătit pentru descărcare.","ready-help");}ui.generated=true;}catch(error){reportDownloadError(error);}finally{ui.busy=false;syncWorkflow();}}
$("#sources")?.addEventListener("change",readSources);["#project-name","#client-name","#report-date","#report-context","#exercise-list","#other-instruments","#conclusions","#benchmark-low","#benchmark-high"].forEach(selector=>$(selector)?.addEventListener("input",invalidateData));["#renderer-bhb","#renderer-trend","#delivery-whole","#delivery-split"].forEach(selector=>$(selector)?.addEventListener("change",updateChoice));$("#issue-search")?.addEventListener("input",event=>{ui.reviewSearch=event.target.value;ui.activeIssue=null;renderReview();});document.querySelectorAll("[data-review-filter]").forEach(button=>button.addEventListener("click",()=>{ui.reviewFilter=button.dataset.reviewFilter;ui.activeIssue=null;renderReview();}));$("#to-step-2")?.addEventListener("click",()=>setStep(2));$("#to-step-3")?.addEventListener("click",()=>setStep(3));$("#to-step-4")?.addEventListener("click",()=>setStep(4));document.querySelectorAll("[data-go-step]").forEach(button=>button.addEventListener("click",()=>setStep(button.dataset.goStep)));document.querySelectorAll("#workflow-steps [data-step]").forEach(button=>button.addEventListener("click",()=>setStep(button.dataset.step)));$("#reset")?.addEventListener("click",()=>{clearDownload();files=[];ui.step=1;ui.renderer="bhb";ui.delivery="whole";ui.acknowledgedWarnings.clear();ui.corrections={values:{}};ui.activeIssue=null;ui.activeGroup="";ui.reviewSearch="";ui.reviewFilter="open";ui.generated=false;$("#sources").value="";["#project-name","#client-name","#report-date","#report-context","#exercise-list","#other-instruments","#conclusions"].forEach(selector=>{const input=$(selector);if(input)input.value="";});if($("#benchmark-low"))$("#benchmark-low").value="2.75";if($("#benchmark-high"))$("#benchmark-high").value="3.5";if($("#renderer-bhb"))$("#renderer-bhb").checked=true;if($("#delivery-whole"))$("#delivery-whole").checked=true;render();});$("#xlsx")?.addEventListener("click",()=>createDownload("xlsx"));$("#pptx-whole")?.addEventListener("click",()=>createDownload("whole"));$("#pptx-main")?.addEventListener("click",()=>createDownload("main"));$("#pptx-appendix")?.addEventListener("click",()=>createDownload("appendix"));render();window.__grfBooted?.();
